### ISSUE TITLE
GIT Flow

### ISSUE THREAD

**Issue by fernandoseguim** [Cappta/best-practices#25]
Pessoal, sugiro adotarmos o padrão de nomenclatura de branches o recomendado no [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), com o intuito de organizar melhor as ramificações do projeto e consequentemente os releases (mantendo a boa prática adotada no GP de criar tags).
 
de maneira geral a organização ficaria assim:

A branch **master** reflete o código que está em produção
Uma branch **develop** criada a partir da master 
Branches  **feature/*** são criadas a partir da develop e quando uma feature for concluída ela é mergeada na branch develop 
Branches **release/*** são criadas a partir da develop e quando uma release for encerrada ela é mergeada na master e na develop

se for necessário aplicar correções no código em produção, criamos branches **hotfix/*** a partir da master e uma vez que a correção estiver completa, a branch é mergeada na develop e na master 

No nosso contexto, podemos adotar o seguinte padrão:

**master**
**develop**
**feature/**_< SIGLA DO PROJETO >-< NÚMERO DO ESTÓRIA >_ Ex: feature/GM-44
**release/**_< RELEASE VERSION >_ Ex: release/1.0.1
**hotfix/**_< SIGLA DO PROJETO >-< NÚMERO DO ISSUE >_ Ex: feature/GM-74

**Comment by daniellessio** [comment]
Para boas práticas de git linkamos a convenção da StoneCo na nossa documentação, que da esse mesmo direcionamento para nomenclatura de _branchs_ e vai mais além em outros pontos como, por exemplo, padrão de mensagens de commit, fluxo de merge, etc. Depois dá uma olhada, a documentação deles é bem massa.
